---
- hosts: dev
  gather_facts: no
  tasks:
    - name: Install java
      shell: yum install java-1.8.0-openjdk -y
      ignore_errors: yes
      become: true
      
    - name: copy war file
      copy:
        src: "{{ workspace }}/gameoflife-0.0.1.war"
        dest: "/tmp/apache-tomcat-9.0.10/webapps/gameoflife-0.0.1.war" 
        mode: 0777
        
    - name: Start Tomcat server
      shell: cd "/tmp/apache-tomcat-9.0.10/bin/; nohup ./startup.sh &"
      become: true
      
    - name: Start Tomcat
      ExecStart=/opt/tomcat/apache-tomcat-8.0.47/bin/startup.sh   
           
      
      
      
