---
- hosts: dev
  gather_facts: no
  vars:
    tomcat_path: "/tmp/apache-tomcat-9.0.10"
    
  tasks:
    - name: Install java
      shell: yum install java-1.8.0-openjdk -y
      ignore_errors: yes
      become: true
      
    - name: copy war file
      copy:
        src: "{{ workspace }}/gameoflife-0.0.1.war"
        dest: "/tmp/apache-tomcat-9.0.10/webapps/gameoflife-0.0.1.war" 
        mode: 0777
        
        
    - name: ==> startup tomcat , path = {{ tomcat_path }}/bin/startup.sh
      shell: setsid /bin/sh -i -c "{{ tomcat_path }}/bin/startup.sh"
           
      
      
      
